[project]
name = "pypi-fairylandfuture"
version = "1.3.1"
description = ""
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohappyeyeballs==2.4.6",
    "aiohttp==3.11.12",
    "aiomysql==0.2.0",
    "aiosignal==1.3.2",
    "amqp==5.3.1",
    "asgiref==3.8.1",
    "astroid==3.3.8",
    "asttokens==3.0.0",
    "attrs==25.1.0",
    "autopep8==2.3.2",
    "backcall==0.2.0",
    "beautifulsoup4==4.13.3",
    "billiard==4.2.1",
    "black==25.1.0",
    "bleach==6.2.0",
    "build==1.2.2.post1",
    "celery==5.4.0",
    "certifi==2025.1.31",
    "cffi==1.17.1",
    "charset-normalizer==3.4.1",
    "click==8.1.8",
    "click-didyoumean==0.3.1",
    "click-plugins==1.1.1",
    "click-repl==0.3.0",
    "colorama==0.4.6",
    "coreapi==2.3.3",
    "coreschema==0.0.4",
    "cryptography==44.0.1",
    "dbutils==3.1.0",
    "decorator==5.1.1",
    "defusedxml==0.7.1",
    "dill==0.3.9",
    "django==5.1.6",
    "django-celery-results==2.5.1",
    "django-cors-headers==4.7.0",
    "django-extensions==3.2.3",
    "django-filter==25.1",
    "django-redis==5.4.0",
    "django-simpleui==2025.1.13",
    "django-tenant-schemas==1.12.0",
    "django-tenants==3.7.0",
    "djangorestframework==3.15.2",
    "docopt==0.6.2",
    "drf-spectacular==0.28.0",
    "drf-yasg==1.21.8",
    "elastic-transport==8.17.0",
    "elasticsearch==8.17.1",
    "events==0.5",
    "executing==2.2.0",
    "faker==36.1.1",
    "fastjsonschema==2.21.1",
    "flake8==7.1.2",
    "frozenlist==1.5.0",
    "greenlet==3.1.1",
    "idna==3.10",
    "inflection==0.5.1",
    "ipython==8.12.3",
    "isort==6.0.0",
    "itypes==1.2.0",
    "jedi==0.19.2",
    "jinja2==3.1.5",
    "jsonschema==4.23.0",
    "jsonschema-specifications==2024.10.1",
    "jupyter-client==8.6.3",
    "jupyter-core==5.7.2",
    "jupyterlab-pygments==0.3.0",
    "kafka-python==2.0.3",
    "kombu==5.4.2",
    "loguru==0.7.3",
    "markdown==3.7",
    "markupsafe==3.0.2",
    "matplotlib-inline==0.1.7",
    "mccabe==0.7.0",
    "mistune==3.1.1",
    "multidict==6.1.0",
    "mypy==1.15.0",
    "mypy-extensions==1.0.0",
    "mysql-connector-python==9.2.0",
    "nbclient==0.10.2",
    "nbconvert==7.16.6",
    "nbformat==5.10.4",
    "netifaces==0.11.0",
    "opensearch-py==2.8.0",
    "ordered-set==4.1.0",
    "packaging==24.2",
    "pandocfilters==1.5.1",
    "parso==0.8.4",
    "pathspec==0.12.1",
    "pickleshare==0.7.5",
    "pigar==2.1.7",
    "pip-autoremove==0.10.0",
    "pip-review==1.3.0",
    "pip-tools==7.4.1",
    "pipdeptree==2.25.0",
    "pipreqs==0.5.0",
    "platformdirs==4.3.6",
    "prompt-toolkit==3.0.50",
    "propcache==0.2.1",
    "psycopg2==2.9.10",
    "psycopg2-binary==2.9.10",
    "pure-eval==0.2.3",
    "pycodestyle==2.12.1",
    "pycparser==2.22",
    "pydocstyle==6.3.0",
    "pyflakes==3.2.0",
    "pygments==2.19.1",
    "pylama==8.4.1",
    "pylint==3.3.4",
    "pymysql==1.1.1",
    "pypinyin==0.53.0",
    "pyproject-hooks==1.2.0",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.0.1",
    "pytz==2025.1",
    "pywin32==308",
    "pyyaml==6.0.2",
    "pyzmq==26.2.1",
    "redis==5.2.1",
    "referencing==0.36.2",
    "requests==2.32.3",
    "rpds-py==0.22.3",
    "six==1.17.0",
    "snowballstemmer==2.2.0",
    "soupsieve==2.6",
    "sqlalchemy==2.0.38",
    "sqlparse==0.5.3",
    "stack-data==0.6.3",
    "tinycss2==1.4.0",
    "tomlkit==0.13.2",
    "tornado==6.4.2",
    "traitlets==5.14.3",
    "typing-extensions==4.12.2",
    "tzdata==2025.1",
    "uritemplate==4.1.1",
    "urllib3==2.3.0",
    "uv==0.6.1",
    "vine==5.1.0",
    "wcwidth==0.2.13",
    "webencodings==0.5.1",
    "wheel==0.45.1",
    "win32-setctime==1.2.0",
    "yarg==0.1.9",
    "yarl==1.18.3",
]
